[[module.imports]]
path = "github.com/razonyang/hb"

[[module.imports]]
path = "github.com/razonyang/hb/modules/docs"

[params.hugopress.modules.hb-docs-doc-featured-image.hooks.hb-docs-doc-content-begin]
