[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb/modules/breadcrumb"

[[module.imports]]
path = "github.com/razonyang/hb/modules/docs"

[params.hugopress.modules.hb-docs-breadcrumb.hooks.hb-docs-main-begin]
