version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/modules/blog"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/modules/meta/recommended"
    schedule:
      interval: "daily"
