[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb/modules/docs"

[[module.imports]]
path = "github.com/razonyang/hb/modules/disqus"

[params.hugopress.modules.hb-docs-comments-disqus.hooks.hb-docs-doc-comments]
