[[module.imports]]
path = "github.com/razonyang/hb/modules/blog"

[[module.imports]]
path = "github.com/razonyang/hb/modules/heading-sign"

[params.hb.heading_sign.containers.".hb-blog-post-content"]
