[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/alternatives"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/base"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/favicons"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/open-graph"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/schema"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/translations"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/twitter-cards"
