[[module.imports]]
path = "github.com/razonyang/hb"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[params.hugopress.modules.hb-noscript.hooks.body-begin]
weight = 1
cacheable = true
