[params.hugopress.modules.hb-blog-post-nav.hooks.hb-blog-post-content-end]

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[[module.imports]]
path = "github.com/razonyang/hb/modules/blog"

[[module.imports]]
path = "github.com/razonyang/hugopress"
