[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/razonyang/hugo-mod-seo/modules/base"

[[module.imports]]
path = "github.com/razonyang/hb/modules/header"

[[module.imports]]
path = "github.com/razonyang/hb/modules/footer"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[params.hb.base.full_width]
types = ["docs"]
# kinds = ["home"]
# sections = ["docs", "notes"]

[params.hb.terms]
paginate = 9
