[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb"

[[module.imports]]
path = "github.com/razonyang/hb/modules/blog"

[[module.imports]]
path = "github.com/razonyang/hb/modules/disqus"

[params.hugopress.modules.hb-blog-comments-disqus.hooks.hb-blog-post-comments]
