[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb/modules/header"

[[module.imports]]
path = "github.com/razonyang/hb/modules/socials"

[params.hugopress.modules.hb-header-socials.hooks.hb-header-panel]
weight = 1
cacheable = true
