[params.hugopress.modules.hb-blog-breadcrumb.hooks.hb-blog-main-begin]

[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb/modules/breadcrumb"

[[module.imports]]
path = "github.com/razonyang/hb/modules/blog"
