[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb/modules/blog"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[params.hugopress.modules.hb-docs.hooks.hb-header-nav-begin]

[params.hb.docs]
date_format = ":date_long"
