[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hb"

[[module.imports]]
path = "github.com/razonyang/hb/modules/utterances"

[[module.imports]]
path = "github.com/razonyang/hb/modules/blog"

[params.hugopress.modules.hb-blog-utterances.hooks.hb-blog-post-comments]
